# Generated by Django 3.1.1 on 2020-09-05 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access_Levels',
            fields=[
                ('access_level_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Changelog',
            fields=[
                ('changelog_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateField()),
                ('description', models.CharField(max_length=250)),
                ('complete', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Changelog_Categories',
            fields=[
                ('changelog_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=75)),
                ('contact_name', models.CharField(max_length=75)),
                ('address', models.CharField(max_length=75)),
                ('city', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=6)),
                ('phone', models.CharField(max_length=14)),
                ('fax', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=45)),
                ('website', models.CharField(max_length=50)),
                ('logo_image', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Company_Categories',
            fields=[
                ('company_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Expense_Categories',
            fields=[
                ('expense_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Sites',
            fields=[
                ('project_site_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=75)),
                ('city', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=6)),
                ('access_code', models.CharField(max_length=10)),
                ('map_link', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('sku_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
                ('abbreviation', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('term_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=14)),
                ('phone_ext', models.CharField(max_length=6)),
                ('email', models.CharField(max_length=45)),
                ('access_level_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='invoicing.access_levels')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='invoicing.companies')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('man_year', models.IntegerField()),
                ('make', models.CharField(max_length=45)),
                ('model', models.CharField(max_length=45)),
                ('submodel', models.CharField(max_length=45)),
                ('engine', models.CharField(max_length=150)),
                ('notes', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Access_Level',
        ),
        migrations.AddField(
            model_name='project_sites',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='invoicing.states'),
        ),
        migrations.AddField(
            model_name='companies',
            name='company_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='invoicing.company_categories'),
        ),
        migrations.AddField(
            model_name='companies',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='invoicing.states'),
        ),
        migrations.AddField(
            model_name='changelog',
            name='changelog_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='invoicing.changelog_categories'),
        ),
    ]
