# Generated by Django 3.1.1 on 2020-09-05 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_auto_20200905_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('bid_id', models.AutoField(primary_key=True, serialize=False)),
                ('bid_date', models.DateField()),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('approve', models.IntegerField()),
                ('denied', models.IntegerField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='invoicing.companies')),
                ('project_site_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='invoicing.project_sites')),
                ('sku_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='invoicing.sku')),
            ],
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('receipts', models.IntegerField()),
                ('images', models.IntegerField()),
                ('image_links', models.TextField()),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('loan_paid', models.IntegerField()),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('interest_paid', models.IntegerField()),
                ('complete', models.IntegerField()),
                ('paid', models.IntegerField()),
                ('paid_checknum', models.CharField(max_length=50)),
                ('paid_date', models.DateField()),
                ('project_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('save_tax', models.DecimalField(decimal_places=2, max_digits=8)),
                ('actual_net', models.DecimalField(decimal_places=2, max_digits=8)),
                ('bid_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='invoicing.bids')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='invoicing.companies')),
            ],
        ),
        migrations.CreateModel(
            name='Mileage',
            fields=[
                ('mileage_id', models.AutoField(primary_key=True, serialize=False)),
                ('drive_date', models.DateField()),
                ('start_mileage', models.IntegerField()),
                ('end_milage', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('notes', models.CharField(max_length=150)),
                ('invoice_id1', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='invoice_id1', to='invoicing.invoices')),
                ('invoice_id2', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='invoice_id2', to='invoicing.invoices')),
                ('invoice_id3', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='invoice_id3', to='invoicing.invoices')),
                ('project_site_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='invoicing.project_sites')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='invoicing.vehicles')),
            ],
        ),
        migrations.AddField(
            model_name='invoices',
            name='mileage_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='invoicing.mileage'),
        ),
        migrations.AddField(
            model_name='invoices',
            name='project_site_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='invoicing.project_sites'),
        ),
        migrations.AddField(
            model_name='invoices',
            name='sku_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='invoicing.sku'),
        ),
        migrations.AddField(
            model_name='invoices',
            name='term_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='invoicing.terms'),
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('expense_id', models.AutoField(primary_key=True, serialize=False)),
                ('pdate', models.DateField()),
                ('name', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ytax', models.IntegerField()),
                ('tax', models.DecimalField(decimal_places=5, max_digits=12)),
                ('total', models.DecimalField(decimal_places=5, max_digits=12)),
                ('receipt_reference', models.CharField(max_length=100)),
                ('receipt_image', models.TextField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='invoicing.companies')),
                ('expense_category_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='invoicing.expense_categories')),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='invoicing.invoices')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='invoicing.vehicles')),
            ],
        ),
    ]
